/**
 * Prismatic — Pre-built Clash & Compare Data
 * Static data for Clash Arena and Compare pages.
 * Does NOT import PERSONA_LIST to avoid SSG evaluation issues.
 */

export const PREMADE_CLASHES = [
  {
    id: 'jobs-vs-bezos',
    title: '乔布斯 vs 贝索斯',
    subtitle: '产品主义 vs 用户至上主义',
    personaA: 'steve-jobs',
    personaAId: 'steve-jobs',
    personaAName: 'Steve Jobs',
    personaANameZh: '史蒂夫·乔布斯',
    personaAAvatar: '🍎',
    personaB: 'jeff-bezos',
    personaBId: 'jeff-bezos',
    personaBName: 'Jeff Bezos',
    personaBNameZh: '杰夫·贝索斯',
    personaBAvatar: '📦',
    topic: '「用户体验」与「客户至上」哪个是商业世界的终极奥义？',
  },
  {
    id: 'dalio-vs-thiel',
    title: '达里奥 vs 彼得·蒂尔',
    subtitle: '原则驱动 vs 秘密驱动',
    personaA: 'ray-dalio',
    personaAId: 'ray-dalio',
    personaAName: 'Ray Dalio',
    personaANameZh: '雷·达里奥',
    personaAAvatar: '⚖️',
    personaB: 'peter-thiel',
    personaBId: 'peter-thiel',
    personaBName: 'Peter Thiel',
    personaBNameZh: '彼得·蒂尔',
    personaBAvatar: '🧠',
    topic: '成功是因为遵循原则，还是因为发现了别人忽视的秘密？',
  },
  {
    id: 'buffett-vs-munger',
    title: '巴菲特 vs 芒格',
    subtitle: '价值投资双雄',
    personaA: 'warren-buffett',
    personaAId: 'warren-buffett',
    personaAName: 'Warren Buffett',
    personaANameZh: '沃伦·巴菲特',
    personaAAvatar: '🎯',
    personaB: 'charlie-munger',
    personaBId: 'charlie-munger',
    personaBName: 'Charlie Munger',
    personaBNameZh: '查理·芒格',
    personaBAvatar: '📚',
    topic: '在市场极度贪婪时保持恐惧，与在别人恐惧时保持贪婪，哪一个更难？',
  },
  {
    id: 'musk-vs-altman',
    title: '马斯克 vs 萨姆·奥特曼',
    subtitle: 'AI 安全的两个极端',
    personaA: 'elon-musk',
    personaAId: 'elon-musk',
    personaAName: 'Elon Musk',
    personaANameZh: '埃隆·马斯克',
    personaAAvatar: '🚀',
    personaB: 'sam-altman',
    personaBId: 'sam-altman',
    personaBName: 'Sam Altman',
    personaBNameZh: '萨姆·奥特曼',
    personaBAvatar: '🤖',
    topic: 'AI 发展应该加速还是谨慎？开源是人类的希望还是灾难的开端？',
  },
  {
    id: 'graham-vs-thiel',
    title: '保罗·格雷厄姆 vs 彼得·蒂尔',
    subtitle: 'Startup 的两种哲学',
    personaA: 'paul-graham',
    personaAId: 'paul-graham',
    personaAName: 'Paul Graham',
    personaANameZh: '保罗·格雷厄姆',
    personaAAvatar: '✍️',
    personaB: 'peter-thiel',
    personaBId: 'peter-thiel',
    personaBName: 'Peter Thiel',
    personaBNameZh: '彼得·蒂尔',
    personaBAvatar: '🧠',
    topic: '创业公司应该快速迭代 MVP，还是追求一开始就做不可能的事？',
  },
  {
    id: 'feynman-vs-einstein',
    title: '费曼 vs 爱因斯坦',
    subtitle: '科学直觉 vs 数学严谨',
    personaA: 'richard-feynman',
    personaAId: 'richard-feynman',
    personaAName: 'Richard Feynman',
    personaANameZh: '理查德·费曼',
    personaAAvatar: '⚛️',
    personaB: 'einstein',
    personaBId: 'einstein',
    personaBName: 'Albert Einstein',
    personaBNameZh: '阿尔伯特·爱因斯坦',
    personaBAvatar: '💡',
    topic: '真正的科学突破主要来自大胆的直觉猜想，还是来自严谨的数学推演？',
  },
];

export const PREMADE_COMPARISONS = [
  {
    id: 'ai-replace',
    title: 'AI 会取代人类工作吗？',
    subtitle: '乐观派 vs 悲观派 vs 务实派',
    topic: 'AI 革命在10年内将如何改变就业市场？哪些工作最危险？',
    personas: ['sam-altman', 'elon-musk', 'warren-buffett'],
    tags: ['AI', '就业', '未来'],
  },
  {
    id: 'startup-advice',
    title: '创业第一课',
    subtitle: '不同流派的投资哲学',
    topic: '第一次创业最重要的是什么？是找到Product-Market Fit，还是团队，还是融资时机？',
    personas: ['paul-graham', 'peter-thiel', 'warren-buffett'],
    tags: ['创业', '投资', '战略'],
  },
  {
    id: 'china-us-relations',
    title: '中美博弈',
    subtitle: '三位思想家的地缘视角',
    topic: '中美关系未来10年的走向？脱钩不可避免还是可以通过商业互利避免？',
    personas: ['ray-dalio', 'peter-thiel', 'warren-buffett'],
    tags: ['地缘政治', '经济', '全球化'],
  },
  {
    id: 'bitcoin-future',
    title: '比特币的终极命运',
    subtitle: '价值存储 vs 泡沫 vs 变革力量',
    topic: '比特币在未来货币体系中的角色：会成为数字黄金，还是最终归零？',
    personas: ['elon-musk', 'warren-buffett', 'peter-thiel'],
    tags: ['加密货币', '投资', '金融'],
  },
  {
    id: 'meaning-of-life',
    title: '人生的意义是什么？',
    subtitle: '哲学家 vs 科学家 vs 实践者',
    topic: '在人工智能时代，「人生意义」这个命题是否还有意义？',
    personas: ['marcus-aurelius', 'alan-watts', 'steve-jobs'],
    tags: ['哲学', 'AI', '意义'],
  },
];
