/**
 * Lightweight Confidence Scores for listing/display pages
 * Standalone data - NO import from confidence.ts to avoid bundling full score objects
 */

export const CONFIDENCE_LIGHT: Record<string, number> = {
  "aleister-crowley": 87,
  "carl-jung": 88,
  "donald-trump": 88,
  "epictetus": 88,
  "han-fei-zi": 87,
  "jack-ma": 86,
  "journey-west": 88,
  "mo-zi": 88,
  "ni-haixia": 87,
  "qian-xuesen": 84,
  "qu-yuan": 86,
  "sun-wukong": 88,
  "three-kingdoms": 87,
  "tripitaka": 86,
  "wang-dongyue": 89,
  "zhang-xuefeng": 88,
  "zhu-bajie": 88,
  "zhuge-liang": 86,
  "andrej-karpathy": 0,
  "cao-cao": 0,
  "huangdi-neijing": 0,
  "ilya-sutskever": 76,
  "john-dee": 0,
  "john-maynard-keynes": 0,
  "kant": 0,
  "li-chunfeng": 0,
  "lin-yutang": 0,
  "liu-bei": 0,
  "marcus-aurelius-stoic": 0,
  "mencius": 0,
  "mrbeast": 0,
  "osamu-dazai": 0,
  "records-grand-historian": 0,
  "shao-yong": 0,
  "xiang-yu": 0,
  "yuan-tiangang": 0,
  "zhang-yiming": 78,
  "wittgenstein": 79,
  "elon-musk": 80,
  "peter-thiel": 76,
  "steve-jobs": 82,
  "naval-ravikant": 77,
  "charlie-munger": 85,
  "paul-graham": 78,
  "jeff-bezos": 74,
  "ray-dalio": 75,
  "jensen-huang": 80,
  "sam-altman": 73,
  "hui-neng": 70,
  "feynman": 84,
  "warren-buffett": 30,
  "confucius": 67,
  "lao-zi": 66,
  "zhuang-zi": 66,
  "sun-tzu": 69,
  "socrates": 65,
  "seneca": 67,
  "marcus-aurelius": 72,
  "alan-turing": 66,
  "nikola-tesla": 61,
  "einstein": 61,
  "nassim-taleb": 65,
  "sima-qian": 66,
  "alan-watts": 82,
  "jiqun": 85,
};
