/**
 * Prismatic — Persona Confidence Scores
 * Based on persona-training-status analysis
 * Generated: 2026-04-12
 */

export interface ConfidenceScore {
  overall: number;
  dataCoverage: number;
  rawMaterial: number;
  timeSpan: number;
  contentDiversity: number;
  sourceVerifiability: number;
  starRating: 1 | 2 | 3 | 4 | 5;
  dataSources: {
    type: string;
    source: string;
    quantity: string;
    quality: string;
  }[];
  corpusPath?: string;
  version: string;
  mainGaps: string[];
  priority: 'high' | 'medium' | 'low';
}

export const PERSONA_CONFIDENCE: Record<string, ConfidenceScore> = {
  'jiqun': {
    overall: 96,
    dataCoverage: 95,
    rawMaterial: 95,
    timeSpan: 98,
    contentDiversity: 98,
    sourceVerifiability: 95,
    starRating: 5,
    version: '2.1',
    corpusPath: 'scrapers/济群法师微博/济群法师_微博全量/济群法师_微博_全量.json',
    priority: 'low',
    dataSources: [
      { type: '微博全量', source: '新浪微博全量数据 (2009-2026)', quantity: '9,666 条', quality: '5' },
      { type: '核心著作', source: '12 本人生佛教系列+修学引导系列', quantity: '约 200 万字', quality: '5' },
      { type: '访谈记录', source: '12 篇核心访谈', quantity: '全量', quality: '5' },
      { type: '讲座足迹', source: '100+ 场讲座', quantity: '主要场次', quality: '4' },
    ],
    mainGaps: ['需要季度同步新增微博'],
  },
  'charlie-munger': {
    overall: 92,
    dataCoverage: 95,
    rawMaterial: 90,
    timeSpan: 95,
    contentDiversity: 88,
    sourceVerifiability: 92,
    starRating: 5,
    version: '3.0',
    corpusPath: 'scrapers/training_data/raw/charlie-munger/all_meetings.txt',
    priority: 'low',
    dataSources: [
      { type: '股东大会记录', source: 'Berkshire Hathaway 官方年会转录', quantity: '1987-2022 (35 年+)', quality: '5' },
      { type: "Poor Charlie's Almanack", source: '自费购买纸质版', quantity: '全量原文', quality: '5' },
      { type: 'Daily Journal 年会', source: 'Daily Journal 官网转录', quantity: '2019-2022 完整转录', quality: '4' },
      { type: 'Wesco Financial 会议', source: '同上', quantity: '1990s-2000s', quality: '3' },
    ],
    mainGaps: ['2023-2024 DJCO 年会记录未获取'],
  },
  'paul-graham': {
    overall: 90,
    dataCoverage: 88,
    rawMaterial: 85,
    timeSpan: 90,
    contentDiversity: 92,
    sourceVerifiability: 95,
    starRating: 5,
    version: '3.0',
    corpusPath: 'scrapers/training_data/raw/paul-graham/ (229 篇)',
    priority: 'low',
    dataSources: [
      { type: 'Essays', source: '博客全部文章 (229篇)', quantity: '229 篇 (3.5 MB)', quality: '5' },
      { type: 'YC 创业课', source: 'YC 官方讲座', quantity: '20+ 场', quality: '4' },
      { type: 'Founder Mode', source: '博客文章', quantity: '1 篇', quality: '4' },
      { type: 'Twitter 推文', source: '推文归档 (待)', quantity: '~3,000 条', quality: '待获取' },
    ],
    mainGaps: ['Twitter 推文未获取'],
  },
  'marcus-aurelius': {
    overall: 92,
    dataCoverage: 95,
    rawMaterial: 90,
    timeSpan: 95,
    contentDiversity: 75,
    sourceVerifiability: 95,
    starRating: 5,
    version: '1.0',
    priority: 'high',
    dataSources: [
      { type: 'Meditations', source: 'The-Digital-Stoic-Library', quantity: '全12卷希腊语原文+英译+注疏', quality: '5' },
      { type: '多译本对照', source: 'Standard Ebooks', quantity: 'George Long等多译本', quality: '5' },
    ],
    mainGaps: ['希腊语原文深度语料库待建立'],
  },
  'epictetus': {
    overall: 88,
    dataCoverage: 90,
    rawMaterial: 85,
    timeSpan: 95,
    contentDiversity: 70,
    sourceVerifiability: 90,
    starRating: 5,
    version: '1.0',
    priority: 'high',
    dataSources: [
      { type: 'Enchiridion', source: 'The-Digital-Stoic-Library', quantity: '全53章希腊语原文+英译', quality: '5' },
      { type: 'Discourses', source: 'The-Digital-Stoic-Library', quantity: '全量英译对照', quality: '4' },
    ],
    mainGaps: ['希腊语原文 Discourses 待补充'],
  },
  // ─── ⭐⭐⭐⭐ 高置信度 ────────────────────────────────────────────────────
  'naval': {
    overall: 84,
    dataCoverage: 80,
    rawMaterial: 82,
    timeSpan: 85,
    contentDiversity: 88,
    sourceVerifiability: 85,
    starRating: 4,
    version: '3.0',
    corpusPath: 'scrapers/training_data/raw/naval-ravikant/ (2.5 MB)',
    priority: 'medium',
    dataSources: [
      { type: 'How to Get Rich', source: '博客文章', quantity: '全文 (~2 MB)', quality: '5' },
      { type: '博客文章', source: '博客文章', quantity: '10 篇主帖', quality: '4' },
      { type: 'The Almanack', source: 'Eric Jorgenson 整理出版', quantity: '全量', quality: '4' },
      { type: 'Joe Rogan Podcast', source: 'Lex Fridman 转录', quantity: '2 期', quality: '3' },
    ],
    mainGaps: ['Twitter 推文未获取', 'Tim Ferriss 播客未获取'],
  },
  'elon-musk': {
    overall: 82,
    dataCoverage: 78,
    rawMaterial: 95,
    timeSpan: 80,
    contentDiversity: 75,
    sourceVerifiability: 82,
    starRating: 4,
    version: '3.0',
    corpusPath: 'scrapers/training_data/raw/elon-musk/ (17 MB)',
    priority: 'medium',
    dataSources: [
      { type: '全量推文', source: 'Twitter API 归档', quantity: '87,921 条 (2009-2025)', quality: '4' },
      { type: '高赞推文', source: '同上人工筛选', quantity: '500 条 (赞>1000)', quality: '5' },
      { type: 'Isaacson 传记', source: 'Walter Isaacson (2023)', quantity: '全量', quality: '3' },
      { type: 'Joe Rogan 访谈', source: 'Lex Fridman 转录', quantity: '1 期', quality: '3' },
    ],
    mainGaps: ['Tesla 财报会议字幕未获取', 'Twitter收购案内部邮件未获取'],
  },
  'alan-watts': {
    overall: 82,
    dataCoverage: 80,
    rawMaterial: 85,
    timeSpan: 90,
    contentDiversity: 80,
    sourceVerifiability: 75,
    starRating: 4,
    version: '1.0',
    priority: 'high',
    dataSources: [
      { type: 'alanwatts.org', source: 'Alan Watts Organization', quantity: '200+ 讲座录音转录', quality: '4' },
      { type: 'Uutter 转录', source: 'asktmk.com', quantity: '56,238 条记录', quality: '4' },
    ],
    mainGaps: ['视频字幕批量获取', '1953年前早期讲座'],
  },
  'peter-thiel': {
    overall: 88,
    dataCoverage: 90,
    rawMaterial: 85,
    timeSpan: 80,
    contentDiversity: 88,
    sourceVerifiability: 90,
    starRating: 4,
    version: '1.0',
    priority: 'high',
    dataSources: [
      { type: 'Zero to One', source: '书籍', quantity: '全书章节', quality: '5' },
      { type: 'CS183 课程笔记', source: 'apachecn/stanford-cs183-notes', quantity: '19 讲 Markdown', quality: '4' },
      { type: 'CS183b 课程笔记', source: 'apachecn/stanford-cs183-notes', quantity: '多讲', quality: '4' },
      { type: '采访', source: 'Lex Fridman Podcast 等', quantity: '多期', quality: '4' },
    ],
    mainGaps: ['CS183/CS183b 原始录音未获取'],
  },
  'richard-feynman': {
    overall: 78,
    dataCoverage: 80,
    rawMaterial: 90,
    timeSpan: 85,
    contentDiversity: 80,
    sourceVerifiability: 80,
    starRating: 4,
    version: '1.0',
    priority: 'high',
    dataSources: [
      { type: 'Feynman Lectures 书籍', source: 'Manjunath GitHub仓库', quantity: 'Caltech 三卷全量PDF', quality: '5' },
      { type: 'Caltech 录音', source: 'Caltech 官方', quantity: '122 讲录音', quality: '4' },
    ],
    mainGaps: ['Caltech 讲座 HTML 格式批量获取'],
  },
  'ray-dalio': {
    overall: 85,
    dataCoverage: 82,
    rawMaterial: 88,
    timeSpan: 75,
    contentDiversity: 80,
    sourceVerifiability: 88,
    starRating: 4,
    version: '1.0',
    priority: 'high',
    dataSources: [
      { type: 'CEO 语录', source: 'HuggingFace CEO语录集 (803条)', quantity: '803 条', quality: '3' },
      { type: 'Lex Fridman 播客', source: 'Lex Fridman Podcast #54', quantity: '完整转录', quality: '4' },
      { type: 'Principles', source: 'Principles: Life and Work 书籍', quantity: '全书', quality: '4' },
      { type: '经济机器', source: 'Bridgewater 官网', quantity: 'How the Economic Machine Works', quality: '4' },
    ],
    mainGaps: ['Bridgewater 内部会议记录未覆盖', 'Changing World Order 详细内容'],
  },
  'sam-altman': {
    overall: 78,
    dataCoverage: 80,
    rawMaterial: 82,
    timeSpan: 70,
    contentDiversity: 78,
    sourceVerifiability: 80,
    starRating: 4,
    version: '1.0',
    priority: 'high',
    dataSources: [
      { type: 'Lex Fridman 播客', source: 'Lex Fridman #367 & #419', quantity: '两期完整转录', quality: '4' },
      { type: '博客文章', source: 'blog.samaltman.com', quantity: '最新 30 篇', quality: '4' },
      { type: '国会听证', source: 'US Senate 2023', quantity: '听证转录', quality: '4' },
      { type: 'YC 课程', source: 'YC Startup Class Talks', quantity: '多期', quality: '3' },
    ],
    mainGaps: ['Twitter 推文未获取', '博客历史文章未全量'],
  },
  'jeff-bezos': {
    overall: 82,
    dataCoverage: 80,
    rawMaterial: 85,
    timeSpan: 75,
    contentDiversity: 78,
    sourceVerifiability: 85,
    starRating: 4,
    version: '1.0',
    priority: 'high',
    dataSources: [
      { type: '股东信', source: 'Amazon 官方 (1997-2020)', quantity: '1997年&2020年全文', quality: '5' },
      { type: 'Lex Fridman 播客', source: 'Lex Fridman Podcast #60', quantity: '完整转录', quality: '4' },
      { type: 'CEO 语录', source: 'HuggingFace CEO语录集', quantity: '多条', quality: '3' },
      { type: 'Day 1 演讲', source: 'Amazon 全公司大会 2016', quantity: '演讲转录', quality: '4' },
    ],
    mainGaps: ['全部股东信未覆盖', 'Re:Mars 演讲未覆盖'],
  },
  'jensen-huang': {
    overall: 75,
    dataCoverage: 72,
    rawMaterial: 78,
    timeSpan: 70,
    contentDiversity: 72,
    sourceVerifiability: 80,
    starRating: 4,
    version: '1.0',
    priority: 'high',
    dataSources: [
      { type: 'CEO 语录', source: 'HuggingFace CEO语录集 (3600条)', quantity: '约 3600 条', quality: '3' },
      { type: 'Lex Fridman 播客', source: 'Lex Fridman Podcast #369', quantity: '完整转录', quality: '4' },
      { type: 'GTC 大会', source: 'NVIDIA 官网', quantity: '近年大会视频字幕', quality: '3' },
    ],
    mainGaps: ['GTC 历史大会字幕未全量获取', '早期采访记录缺失'],
  },
  'jerome-powell': {
    overall: 70,
    dataCoverage: 65,
    rawMaterial: 75,
    timeSpan: 70,
    contentDiversity: 60,
    sourceVerifiability: 80,
    starRating: 4,
    version: '1.0',
    priority: 'medium',
    dataSources: [
      { type: 'CEO 引语数据集', source: 'HuggingFace CEO语录集', quantity: '968 条公开引语', quality: '3' },
      { type: 'FOMC 会议纪要', source: 'Federal Reserve 官网', quantity: '公开纪要', quality: '4' },
    ],
    mainGaps: ['国会听证会全量转录', '采访记录不足'],
  },
  // ─── ⭐⭐⭐ 中置信度 ─────────────────────────────────────────────────────
  'trump': {
    overall: 78,
    dataCoverage: 72,
    rawMaterial: 88,
    timeSpan: 75,
    contentDiversity: 80,
    sourceVerifiability: 75,
    starRating: 4,
    version: '2.0',
    corpusPath: 'scrapers/training_data/raw/donald-trump/ (1.9 MB)',
    priority: 'medium',
    dataSources: [
      { type: '任期前推文', source: 'Twitter 官方归档', quantity: '31,249 条 (2009-2017)', quality: '4' },
      { type: '任期推文', source: '同上', quantity: '23,075 条 (2017-2021)', quality: '4' },
      { type: 'Truth Social 推文', source: 'Truth Social 公开数据', quantity: '18,778 条', quality: '3' },
      { type: '2016 竞选语料', source: '特朗普竞选团队资料', quantity: '1,000+ 篇', quality: '4' },
    ],
    mainGaps: ['Art of the Deal 未全量获取', '2024-2025 竞选语料'],
  },
  'confucius': {
    overall: 78,
    dataCoverage: 80,
    rawMaterial: 75,
    timeSpan: 90,
    contentDiversity: 70,
    sourceVerifiability: 75,
    starRating: 4,
    version: '1.0',
    priority: 'low',
    dataSources: [
      { type: '论语', source: '中华经典古籍库', quantity: '全文', quality: '4' },
      { type: '礼记', source: '中华经典古籍库', quantity: '选读', quality: '3' },
      { type: '史记·孔子世家', source: '史记', quantity: '全文', quality: '3' },
    ],
    mainGaps: ['尚书、诗经原文未全量覆盖'],
  },
  'lao-zi': {
    overall: 76,
    dataCoverage: 78,
    rawMaterial: 75,
    timeSpan: 90,
    contentDiversity: 68,
    sourceVerifiability: 73,
    starRating: 4,
    version: '1.0',
    priority: 'low',
    dataSources: [
      { type: '道德经', source: '中华经典古籍库', quantity: '全文 81 章', quality: '4' },
      { type: '帛书版道德经', source: '手动整理', quantity: '差异对照', quality: '3' },
    ],
    mainGaps: ['列子、淮南子相关引用未覆盖'],
  },
  'seneca': {
    overall: 75,
    dataCoverage: 80,
    rawMaterial: 70,
    timeSpan: 88,
    contentDiversity: 65,
    sourceVerifiability: 72,
    starRating: 4,
    version: '1.0',
    corpusPath: 'scrapers/training_data/raw/seneca/ (1.1 MB)',
    priority: 'low',
    dataSources: [
      { type: 'On the Shortness of Life', source: '古登堡计划免费电子书', quantity: '76,142 字', quality: '4' },
      { type: 'On Anger', source: '古登堡计划免费电子书', quantity: '609,228 字', quality: '4' },
      { type: 'On a Happy Life', source: '古登堡计划免费电子书', quantity: '25,697 字', quality: '3' },
      { type: 'On Benefits', source: '古登堡计划免费电子书', quantity: '45,240 字', quality: '3' },
    ],
    mainGaps: ['Naturales Quaestiones 未覆盖'],
  },
  'warren-buffett': {
    overall: 72,
    dataCoverage: 70,
    rawMaterial: 75,
    timeSpan: 95,
    contentDiversity: 65,
    sourceVerifiability: 70,
    starRating: 4,
    version: '1.0',
    priority: 'medium',
    dataSources: [
      { type: 'CEO 引语数据集', source: 'HuggingFace CEO语录集', quantity: '170 条公开引语', quality: '3' },
      { type: 'Lex Fridman 播客', source: 'Lex Fridman Podcast', quantity: '部分集数', quality: '3' },
    ],
    mainGaps: ['股东大会完整转录未获取', '致股东信全量未获取'],
  },
  'kant': {
    overall: 73,
    dataCoverage: 72,
    rawMaterial: 68,
    timeSpan: 85,
    contentDiversity: 65,
    sourceVerifiability: 75,
    starRating: 3,
    version: '1.0',
    corpusPath: 'scrapers/training_data/raw/kant/ (1.8 MB)',
    priority: 'medium',
    dataSources: [
      { type: 'Critique of Pure Reason', source: '古登堡计划免费电子书', quantity: '1.3M 字', quality: '3' },
      { type: 'Groundwork of Morals', source: '古登堡计划免费电子书', quantity: '199,644 字', quality: '4' },
      { type: 'What is Enlightenment', source: '古登堡计划免费电子书', quantity: '357,878 字', quality: '4' },
    ],
    mainGaps: ['Critique of Judgment 未覆盖', 'Prolegomena 未覆盖'],
  },
  'cao-cao': {
    overall: 60,
    dataCoverage: 55,
    rawMaterial: 55,
    timeSpan: 75,
    contentDiversity: 52,
    sourceVerifiability: 63,
    starRating: 3,
    version: '1.0',
    priority: 'low',
    dataSources: [
      { type: '曹操诗集', source: '中华经典古籍库', quantity: '全量', quality: '4' },
      { type: '三国志·魏书', source: '三国志', quantity: '相关段落', quality: '3' },
    ],
    mainGaps: ['孙子兵法注（曹操）未全量覆盖'],
  },
  'tesla-nikola': {
    overall: 65,
    dataCoverage: 60,
    rawMaterial: 60,
    timeSpan: 80,
    contentDiversity: 55,
    sourceVerifiability: 70,
    starRating: 3,
    version: '1.0',
    corpusPath: 'scrapers/training_data/raw/tesla/My_Inventions.txt (366 KB)',
    priority: 'medium',
    dataSources: [
      { type: 'My Inventions', source: '古登堡计划免费电子书', quantity: '366,279 字', quality: '3' },
      { type: 'Colorado Springs Notes', source: '手动整理', quantity: '摘要级', quality: '2' },
    ],
    mainGaps: ['书信全集未覆盖', 'Nikola Tesla Museum 档案未获取'],
  },
  'einstein': {
    overall: 63,
    dataCoverage: 60,
    rawMaterial: 58,
    timeSpan: 75,
    contentDiversity: 55,
    sourceVerifiability: 68,
    starRating: 3,
    version: '1.0',
    corpusPath: 'scrapers/training_data/raw/einstein/ (316 KB)',
    priority: 'medium',
    dataSources: [
      { type: 'Ideas and Opinions', source: '古登堡计划免费电子书', quantity: '222,427 字', quality: '3' },
      { type: 'The World As I See It', source: '古登堡计划免费电子书', quantity: '92,776 字', quality: '3' },
    ],
    mainGaps: ['相对论论文原文未覆盖', '书信全集未覆盖', 'Schrodinger 信件对话'],
  },
  'steve-jobs': {
    overall: 62,
    dataCoverage: 65,
    rawMaterial: 55,
    timeSpan: 65,
    contentDiversity: 65,
    sourceVerifiability: 60,
    starRating: 3,
    version: '1.0',
    priority: 'medium',
    dataSources: [
      { type: 'Steve Jobs by Walter Isaacson', source: '书籍', quantity: '全量', quality: '4' },
      { type: 'Stanford 毕业典礼', source: '官方视频字幕', quantity: '1 次', quality: '4' },
    ],
    mainGaps: ['All Things D 采访全量', 'Macworld 主题演讲原文'],
  },
  'zhuge-liang': {
    overall: 58,
    dataCoverage: 55,
    rawMaterial: 50,
    timeSpan: 75,
    contentDiversity: 50,
    sourceVerifiability: 60,
    starRating: 2,
    version: '1.0',
    priority: 'low',
    dataSources: [
      { type: '出师表', source: '中华经典古籍库', quantity: '全文', quality: '4' },
      { type: '三国志·蜀书', source: '三国志', quantity: '相关段落', quality: '3' },
    ],
    mainGaps: ['便宜十六策全文未覆盖', '后出师表'],
  },
  'zhang-yiming': {
    overall: 58,
    dataCoverage: 55,
    rawMaterial: 50,
    timeSpan: 70,
    contentDiversity: 60,
    sourceVerifiability: 55,
    starRating: 2,
    version: '1.0',
    priority: 'medium',
    dataSources: [
      { type: '知乎回答', source: '知乎 (手动)', quantity: '数十条', quality: '2' },
      { type: '内部信泄露', source: '网络', quantity: '2-3 封', quality: '2' },
    ],
    mainGaps: ['字节跳动全员会未覆盖', '采访记录严重不足'],
  },
  'zhang-xuefeng': {
    overall: 55,
    dataCoverage: 50,
    rawMaterial: 55,
    timeSpan: 55,
    contentDiversity: 60,
    sourceVerifiability: 55,
    starRating: 2,
    version: '1.0',
    corpusPath: 'scrapers/training_data/raw/zhang-xuefeng/training_corpus.txt',
    priority: 'high',
    dataSources: [
      { type: '高考志愿语录', source: '全网结构化语录整理', quantity: '105 条 (六大分类)', quality: '3' },
      { type: 'B站/抖音视频字幕', source: '视频字幕批量获取 (待)', quantity: '数十条', quality: '待获取' },
    ],
    mainGaps: ['B站/抖音视频字幕未获取', '知乎回答未覆盖'],
  },
  'mrbeast': {
    overall: 52,
    dataCoverage: 45,
    rawMaterial: 55,
    timeSpan: 60,
    contentDiversity: 55,
    sourceVerifiability: 45,
    starRating: 2,
    version: '1.0',
    priority: 'medium',
    dataSources: [
      { type: 'YouTube 视频字幕', source: '视频字幕批量获取 (待)', quantity: '300+ 部', quality: '待获取' },
      { type: 'YouTube 字幕数据集', source: 'YouTube 字幕数据集', quantity: '~800 视频', quality: '3' },
    ],
    mainGaps: ['视频字幕未获取'],
  },
  'sun-tzu': {
    overall: 75,
    dataCoverage: 75,
    rawMaterial: 80,
    timeSpan: 90,
    contentDiversity: 65,
    sourceVerifiability: 75,
    starRating: 4,
    version: '1.0',
    priority: 'low',
    dataSources: [
      { type: '孙子兵法', source: '中华经典古籍库 / chinese-philosophy', quantity: '全文 13 篇', quality: '5' },
      { type: '多注本', source: '十家注等', quantity: '对照参考', quality: '4' },
    ],
    mainGaps: ['竹简本未对照', '先秦诸子引用未覆盖'],
  },
  'zhuang-zi': {
    overall: 78,
    dataCoverage: 80,
    rawMaterial: 78,
    timeSpan: 90,
    contentDiversity: 70,
    sourceVerifiability: 75,
    starRating: 4,
    version: '1.0',
    priority: 'low',
    dataSources: [
      { type: '庄子', source: '中华经典古籍库', quantity: '全文 1M 字符', quality: '4' },
      { type: '内7篇+外15篇+杂篇', source: '同上', quantity: '全量', quality: '4' },
    ],
    mainGaps: ['惠施等论敌语录未分离'],
  },
  'mencius': {
    overall: 73,
    dataCoverage: 72,
    rawMaterial: 70,
    timeSpan: 85,
    contentDiversity: 60,
    sourceVerifiability: 72,
    starRating: 3,
    version: '1.0',
    priority: 'low',
    dataSources: [
      { type: '孟子', source: '中华经典古籍库', quantity: '全文 7 篇', quality: '4' },
      { type: '史记·孟子荀卿列传', source: '史记', quantity: '相关段落', quality: '3' },
    ],
    mainGaps: ['其他典籍引用未覆盖'],
  },
  'mo-zi': {
    overall: 65,
    dataCoverage: 65,
    rawMaterial: 60,
    timeSpan: 80,
    contentDiversity: 55,
    sourceVerifiability: 70,
    starRating: 3,
    version: '1.0',
    priority: 'low',
    dataSources: [
      { type: '墨子', source: '中华经典古籍库', quantity: '主要篇章', quality: '3' },
    ],
    mainGaps: ['部分失传篇章未覆盖'],
  },
  'han-fei-zi': {
    overall: 68,
    dataCoverage: 65,
    rawMaterial: 62,
    timeSpan: 80,
    contentDiversity: 55,
    sourceVerifiability: 70,
    starRating: 3,
    version: '1.0',
    priority: 'low',
    dataSources: [
      { type: '韩非子', source: '中华经典古籍库', quantity: '主要篇章', quality: '3' },
    ],
    mainGaps: ['部分篇章散佚'],
  },
  'qu-yuan': {
    overall: 55,
    dataCoverage: 55,
    rawMaterial: 50,
    timeSpan: 75,
    contentDiversity: 50,
    sourceVerifiability: 60,
    starRating: 2,
    version: '1.0',
    priority: 'low',
    dataSources: [
      { type: '楚辞', source: '中华经典古籍库', quantity: '离骚+九歌等', quality: '4' },
      { type: '史记·屈原贾生列传', source: '史记', quantity: '全文', quality: '3' },
    ],
    mainGaps: ['作品散佚较多'],
  },
  'liu-bei': {
    overall: 55,
    dataCoverage: 50,
    rawMaterial: 45,
    timeSpan: 75,
    contentDiversity: 45,
    sourceVerifiability: 60,
    starRating: 2,
    version: '1.0',
    priority: 'low',
    dataSources: [
      { type: '三国志·蜀书', source: '三国志', quantity: '相关段落', quality: '3' },
      { type: '三国演义', source: '古典文学', quantity: '文学演绎', quality: '2' },
    ],
    mainGaps: ['史料有限，主要依赖三国演义文学形象'],
  },
  'xiang-yu': {
    overall: 50,
    dataCoverage: 45,
    rawMaterial: 40,
    timeSpan: 75,
    contentDiversity: 40,
    sourceVerifiability: 55,
    starRating: 2,
    version: '1.0',
    priority: 'low',
    dataSources: [
      { type: '史记·项羽本纪', source: '史记', quantity: '全文', quality: '4' },
      { type: '汉书·项籍传', source: '汉书', quantity: '相关段落', quality: '3' },
    ],
    mainGaps: ['直接语录有限，多为叙事描述'],
  },
  'hui-neng': {
    overall: 75,
    dataCoverage: 78,
    rawMaterial: 72,
    timeSpan: 85,
    contentDiversity: 70,
    sourceVerifiability: 78,
    starRating: 4,
    version: '1.0',
    priority: 'low',
    dataSources: [
      { type: '六祖坛经', source: '中华经典古籍库', quantity: '全文', quality: '5' },
      { type: '五灯会元', source: '中华经典古籍库', quantity: '相关段落', quality: '4' },
    ],
    mainGaps: ['早期敦煌本与通行本差异未区分'],
  },
  'qian-xuesen': {
    overall: 55,
    dataCoverage: 50,
    rawMaterial: 45,
    timeSpan: 70,
    contentDiversity: 45,
    sourceVerifiability: 60,
    starRating: 2,
    version: '1.0',
    priority: 'medium',
    dataSources: [
      { type: '公开演讲', source: '网络档案', quantity: '部分记录', quality: '3' },
      { type: '工程控制论等著作', source: '公开出版物', quantity: '主要著作', quality: '3' },
    ],
    mainGaps: ['内部档案未覆盖', '书信全集未获取'],
  },
  'andrej-karpathy': {
    overall: 40,
    dataCoverage: 38,
    rawMaterial: 38,
    timeSpan: 55,
    contentDiversity: 38,
    sourceVerifiability: 42,
    starRating: 1,
    version: '1.0',
    priority: 'medium',
    dataSources: [
      { type: 'YouTube 视频', source: '视频字幕批量获取 (待)', quantity: '数十条', quality: '待获取' },
      { type: 'Twitter @karpathy', source: '推文批量获取 (待)', quantity: '~5,000 条', quality: '待获取' },
      { type: '学术论文', source: 'arXiv', quantity: '10+ 篇', quality: '4' },
    ],
    mainGaps: ['Twitter 推文未获取', 'YouTube 字幕未获取'],
  },
  'naval-ravikant': {
    overall: 84,
    dataCoverage: 80,
    rawMaterial: 82,
    timeSpan: 85,
    contentDiversity: 88,
    sourceVerifiability: 85,
    starRating: 4,
    version: '3.0',
    corpusPath: 'scrapers/training_data/raw/naval-ravikant/ (2.5 MB)',
    priority: 'medium',
    dataSources: [
      { type: 'How to Get Rich', source: '博客文章', quantity: '全文 (~2 MB)', quality: '5' },
      { type: '博客文章', source: '博客文章', quantity: '10 篇主帖', quality: '4' },
      { type: 'The Almanack', source: 'Eric Jorgenson 整理出版', quantity: '全量', quality: '4' },
      { type: 'Joe Rogan Podcast', source: 'Lex Fridman 转录', quantity: '2 期', quality: '3' },
    ],
    mainGaps: ['Twitter 推文未获取', 'Tim Ferriss 播客未获取'],
  },
  'nikola-tesla': {
    overall: 65,
    dataCoverage: 60,
    rawMaterial: 60,
    timeSpan: 80,
    contentDiversity: 55,
    sourceVerifiability: 70,
    starRating: 3,
    version: '1.0',
    corpusPath: 'scrapers/training_data/raw/tesla/My_Inventions.txt (366 KB)',
    priority: 'medium',
    dataSources: [
      { type: 'My Inventions', source: '古登堡计划免费电子书', quantity: '366,279 字', quality: '3' },
      { type: 'Colorado Springs Notes', source: '手动整理', quantity: '摘要级', quality: '2' },
    ],
    mainGaps: ['书信全集未覆盖', 'Nikola Tesla Museum 档案未获取'],
  },
  'ilya-sutskever': {
    overall: 40,
    dataCoverage: 35,
    rawMaterial: 30,
    timeSpan: 50,
    contentDiversity: 40,
    sourceVerifiability: 45,
    starRating: 1,
    version: '1.0',
    priority: 'high',
    dataSources: [
      { type: '学术论文', source: '学术论文数据库', quantity: '20+ 篇', quality: '4' },
      { type: '公开访谈', source: 'YouTube', quantity: '3-5 期', quality: '3' },
    ],
    mainGaps: ['OpenAI 内部演讲未获取', 'Twitter 推文未覆盖'],
  },
  'nassim-taleb': {
    overall: 45,
    dataCoverage: 40,
    rawMaterial: 35,
    timeSpan: 55,
    contentDiversity: 50,
    sourceVerifiability: 45,
    starRating: 1,
    version: '1.0',
    priority: 'high',
    dataSources: [
      { type: 'The Black Swan / Antifragile', source: '书籍', quantity: '全量', quality: '4' },
      { type: 'Skin in the Game', source: '书籍', quantity: '全量', quality: '2' },
      { type: '@nntaleb 推文', source: '推文批量获取 (待)', quantity: '~50,000 条', quality: '未获取' },
    ],
    mainGaps: ['@nntaleb 推文全量未获取（最重要缺口）', 'Incerto 系列其他书籍未覆盖'],
  },
  'donald-trump': {
    overall: 78,
    dataCoverage: 72,
    rawMaterial: 88,
    timeSpan: 75,
    contentDiversity: 80,
    sourceVerifiability: 75,
    starRating: 4,
    version: '2.0',
    corpusPath: 'scrapers/training_data/raw/donald-trump/ (1.9 MB)',
    priority: 'medium',
    dataSources: [
      { type: '任期前推文', source: 'Twitter 官方归档', quantity: '31,249 条 (2009-2017)', quality: '4' },
      { type: '任期推文', source: '同上', quantity: '23,075 条 (2017-2021)', quality: '4' },
      { type: 'Truth Social 推文', source: 'Truth Social 公开数据', quantity: '18,778 条', quality: '3' },
      { type: '2016 竞选语料', source: '特朗普竞选团队资料', quantity: '1,000+ 篇', quality: '4' },
    ],
    mainGaps: ['Art of the Deal 未全量获取', '2024-2025 竞选语料'],
  },
  'sun-wukong': {
    overall: 40,
    dataCoverage: 40,
    rawMaterial: 35,
    timeSpan: 85,
    contentDiversity: 45,
    sourceVerifiability: 30,
    starRating: 1,
    version: '1.0',
    priority: 'low',
    dataSources: [
      { type: '西游记', source: '中华经典古籍库', quantity: '百回本', quality: '4' },
    ],
    mainGaps: ['元杂剧西游记未覆盖', '民间传说变体'],
  },
  'zhu-bajie': {
    overall: 30,
    dataCoverage: 30,
    rawMaterial: 25,
    timeSpan: 80,
    contentDiversity: 40,
    sourceVerifiability: 20,
    starRating: 1,
    version: '1.0',
    priority: 'low',
    dataSources: [
      { type: '西游记', source: '中华经典古籍库', quantity: '百回本', quality: '4' },
    ],
    mainGaps: ['仅靠西游记单一来源，需补充民间解读'],
  },
  // ─── 分组/合集人物 ──────────────────────────────────────────────────────────
  // 这类人物代表多个人物的集体智慧，数据覆盖取决于收录范围
  'journey-west': {
    overall: 38,
    dataCoverage: 40,
    rawMaterial: 45,
    timeSpan: 90,
    contentDiversity: 35,
    sourceVerifiability: 35,
    starRating: 1,
    version: '1.0',
    priority: 'low',
    dataSources: [
      { type: '西游记', source: '中华经典古籍库', quantity: '百回本', quality: '4' },
    ],
    mainGaps: ['元杂剧版本未覆盖', '民间变体未区分'],
  },
  'three-kingdoms': {
    overall: 50,
    dataCoverage: 50,
    rawMaterial: 45,
    timeSpan: 75,
    contentDiversity: 45,
    sourceVerifiability: 55,
    starRating: 2,
    version: '1.0',
    priority: 'low',
    dataSources: [
      { type: '三国志', source: '中华经典古籍库', quantity: '全文', quality: '4' },
      { type: '三国演义', source: '古典文学', quantity: '百二十回本', quality: '3' },
    ],
    mainGaps: ['正史与演义混合', '裴注未覆盖'],
  },
  'records-grand-historian': {
    overall: 45,
    dataCoverage: 50,
    rawMaterial: 40,
    timeSpan: 85,
    contentDiversity: 40,
    sourceVerifiability: 55,
    starRating: 2,
    version: '1.0',
    priority: 'low',
    dataSources: [
      { type: '史记', source: '中华经典古籍库', quantity: '本纪12+世家30+列传70', quality: '4' },
    ],
    mainGaps: ['八书部分未覆盖', '裴骃注疏未纳入'],
  },
  'tripitaka': {
    overall: 35,
    dataCoverage: 30,
    rawMaterial: 30,
    timeSpan: 80,
    contentDiversity: 25,
    sourceVerifiability: 30,
    starRating: 1,
    version: '1.0',
    priority: 'low',
    dataSources: [
      { type: '大唐西域记', source: '中华经典古籍库', quantity: '全文', quality: '4' },
      { type: '西游记', source: '中华经典古籍库', quantity: '相关段落', quality: '3' },
    ],
    mainGaps: ['历史原型玄奘语录有限，主要为文学塑造形象'],
  },
  'huangdi-neijing': {
    overall: 48,
    dataCoverage: 50,
    rawMaterial: 42,
    timeSpan: 90,
    contentDiversity: 35,
    sourceVerifiability: 55,
    starRating: 2,
    version: '1.0',
    priority: 'low',
    dataSources: [
      { type: '黄帝内经', source: '中华经典古籍库', quantity: '素问81+灵枢81', quality: '4' },
    ],
    mainGaps: ['历代注疏未纳入', '简帛本差异未对照'],
  },
};

// Top personas for quick display
export const TOP_PERSONAS = [
  'jiqun', 'charlie-munger', 'paul-graham', 'marcus-aurelius', 'epictetus',
  'naval', 'elon-musk', 'alan-watts', 'peter-thiel', 'richard-feynman',
  'ray-dalio', 'jeff-bezos', 'jensen-huang', 'sam-altman'
];

export function getConfidenceLevel(score: number): { label: string; color: string; bgColor: string; borderColor: string } {
  if (score >= 90) return { label: '极高置信度', color: '#10b981', bgColor: 'rgba(16,185,129,0.1)', borderColor: 'rgba(16,185,129,0.3)' };
  if (score >= 75) return { label: '高置信度', color: '#3b82f6', bgColor: 'rgba(59,130,246,0.1)', borderColor: 'rgba(59,130,246,0.3)' };
  if (score >= 60) return { label: '中置信度', color: '#f59e0b', bgColor: 'rgba(245,158,11,0.1)', borderColor: 'rgba(245,158,11,0.3)' };
  if (score >= 45) return { label: '低置信度', color: '#ef4444', bgColor: 'rgba(239,68,68,0.1)', borderColor: 'rgba(239,68,68,0.3)' };
  return { label: '需要完善', color: '#6b7280', bgColor: 'rgba(107,114,128,0.1)', borderColor: 'rgba(107,114,128,0.3)' };
}

