/**
 * Lightweight Persona List for listing/display pages
 * Standalone data - NO import from personas.ts to avoid bundling 1MB of mental models
 */

export interface PersonaListLight {
  id: string;
  slug: string;
  name: string;
  nameZh: string;
  domain: string[];
  tagline: string;
  taglineZh: string;
  gradientFrom: string;
  gradientTo: string;
}

export const PERSONA_LIST_LIGHT: PersonaListLight[] = [
  {
    id: "steve-jobs",
    slug: "steve-jobs",
    name: "Steve Jobs",
    nameZh: "史蒂夫·乔布斯",
    domain: ["philosophy"],
    tagline: "简洁",
    taglineZh: "简洁",
    gradientFrom: "#ef4444",
    gradientTo: "#8b5cf6",
  },
  {
    id: "elon-musk",
    slug: "elon-musk",
    name: "Elon Musk",
    nameZh: "埃隆·马斯克",
    domain: ["philosophy"],
    tagline: "言论自由",
    taglineZh: "言论自由",
    gradientFrom: "#8b5cf6",
    gradientTo: "#8b5cf6",
  },
  {
    id: "charlie-munger",
    slug: "charlie-munger",
    name: "Charlie Munger",
    nameZh: "查理·芒格",
    domain: ["philosophy"],
    tagline: "理性",
    taglineZh: "理性",
    gradientFrom: "#3b82f6",
    gradientTo: "#8b5cf6",
  },
  {
    id: "richard-feynman",
    slug: "richard-feynman",
    name: "Richard Feynman",
    nameZh: "理查德·费曼",
    domain: ["philosophy"],
    tagline: "好奇心",
    taglineZh: "好奇心",
    gradientFrom: "#6366f1",
    gradientTo: "#8b5cf6",
  },
  {
    id: "zhang-yiming",
    slug: "zhang-yiming",
    name: "Zhang Yiming",
    nameZh: "张一鸣",
    domain: ["philosophy"],
    tagline: "通过人工智能创新",
    taglineZh: "通过人工智能创新",
    gradientFrom: "#10b981",
    gradientTo: "#8b5cf6",
  },
  {
    id: "paul-graham",
    slug: "paul-graham",
    name: "Paul Graham",
    nameZh: "保罗·格雷厄姆",
    domain: ["philosophy"],
    tagline: "创新",
    taglineZh: "创新",
    gradientFrom: "#14b8a6",
    gradientTo: "#8b5cf6",
  },
  {
    id: "andrej-karpathy",
    slug: "andrej-karpathy",
    name: "Andrej Karpathy",
    nameZh: "安德烈·卡帕西",
    domain: ["philosophy"],
    tagline: "教育与知识分享",
    taglineZh: "教育与知识分享",
    gradientFrom: "#3b82f6",
    gradientTo: "#8b5cf6",
  },
  {
    id: "nassim-taleb",
    slug: "nassim-taleb",
    name: "Nassim Taleb",
    nameZh: "纳西姆·塔勒布",
    domain: ["philosophy"],
    tagline: "反脆弱性",
    taglineZh: "反脆弱性",
    gradientFrom: "#10b981",
    gradientTo: "#8b5cf6",
  },
  {
    id: "zhang-xuefeng",
    slug: "zhang-xuefeng",
    name: "Zhang Xuefeng",
    nameZh: "张雪峰",
    domain: ["philosophy"],
    tagline: "务实结果",
    taglineZh: "务实结果",
    gradientFrom: "#8b5cf6",
    gradientTo: "#8b5cf6",
  },
  {
    id: "donald-trump",
    slug: "donald-trump",
    name: "Donald Trump",
    nameZh: "唐纳德·特朗普",
    domain: ["negotiation","strategy","leadership"],
    tagline: "交易的艺术",
    taglineZh: "交易的艺术",
    gradientFrom: "#ff6b6b",
    gradientTo: "#ff6b9d",
  },
  {
    id: "mrbeast",
    slug: "mrbeast",
    name: "MrBeast",
    nameZh: "MrBeast",
    domain: ["creativity","strategy"],
    tagline: "注意力工程师",
    taglineZh: "注意力工程师",
    gradientFrom: "#6bcb77",
    gradientTo: "#ffd93d",
  },
  {
    id: "ilya-sutskever",
    slug: "ilya-sutskever",
    name: "Ilya Sutskever",
    nameZh: "伊利亚·苏茨克沃",
    domain: ["philosophy"],
    tagline: "科学突破",
    taglineZh: "科学突破",
    gradientFrom: "#ec4899",
    gradientTo: "#8b5cf6",
  },
  {
    id: "jiqun",
    slug: "jiqun",
    name: "济群法师",
    nameZh: "济群法师",
    domain: ["philosophy"],
    tagline: "觉醒",
    taglineZh: "觉醒",
    gradientFrom: "#8b5cf6",
    gradientTo: "#8b5cf6",
  },
  {
    id: "kant",
    slug: "kant",
    name: "Immanuel Kant",
    nameZh: "伊曼努尔·康德",
    domain: ["philosophy","strategy","ethics"],
    tagline: "康德：敢于求知",
    taglineZh: "康德：敢于求知",
    gradientFrom: "#3b5998",
    gradientTo: "#4a69ad",
  },
  {
    id: "alan-watts",
    slug: "alan-watts",
    name: "Alan Watts",
    nameZh: "阿伦·沃茨",
    domain: ["philosophy","spirituality","zen-buddhism"],
    tagline: "哲学即生活方式",
    taglineZh: "哲学即生活方式",
    gradientFrom: "#e67e22",
    gradientTo: "#d35400",
  },
  {
    id: "jensen-huang",
    slug: "jensen-huang",
    name: "Jensen Huang",
    nameZh: "黄仁勋",
    domain: ["philosophy"],
    tagline: "韧性",
    taglineZh: "韧性",
    gradientFrom: "#8b5cf6",
    gradientTo: "#8b5cf6",
  },
  {
    id: "ni-haixia",
    slug: "ni-haixia",
    name: "Ni Haixia",
    nameZh: "倪海厦",
    domain: ["science","philosophy","education"],
    tagline: "学古不泥，贯通中医与易经",
    taglineZh: "学古不泥，贯通中医与易经",
    gradientFrom: "#c0392b",
    gradientTo: "#e74c3c",
  },
  {
    id: "osamu-dazai",
    slug: "osamu-dazai",
    name: "Osamu Dazai",
    nameZh: "太宰治",
    domain: ["philosophy","creativity","ethics"],
    tagline: "生而为人，我很抱歉",
    taglineZh: "生而为人，我很抱歉",
    gradientFrom: "#4b5563",
    gradientTo: "#9ca3af",
  },
  {
    id: "wang-dongyue",
    slug: "wang-dongyue",
    name: "Wang Dongyue",
    nameZh: "王东岳",
    domain: ["philosophy"],
    tagline: "递弱代偿，物演通变",
    taglineZh: "递弱代偿，物演通变",
    gradientFrom: "#2d1b69",
    gradientTo: "#4c1d95",
  },
  {
    id: "lin-yutang",
    slug: "lin-yutang",
    name: "Lin Yutang",
    nameZh: "林语堂",
    domain: ["philosophy","creativity","education"],
    tagline: "生活的智慧在于顺应生活的本然",
    taglineZh: "生活的智慧在于顺应生活的本然",
    gradientFrom: "#2e7d32",
    gradientTo: "#81c784",
  },
  {
    id: "yuan-tiangang",
    slug: "yuan-tiangang",
    name: "Yuan Tiangang",
    nameZh: "袁天罡",
    domain: ["philosophy","strategy","spirituality"],
    tagline: "龙瞳凤颈，当作天子",
    taglineZh: "龙瞳凤颈，当作天子",
    gradientFrom: "#7b1fa2",
    gradientTo: "#e91e63",
  },
  {
    id: "john-dee",
    slug: "john-dee",
    name: "John Dee",
    nameZh: "John Dee",
    domain: ["philosophy","strategy","science"],
    tagline: "如其在上，如其在下",
    taglineZh: "如其在上，如其在下",
    gradientFrom: "#6a1b9a",
    gradientTo: "#ad1457",
  },
  {
    id: "marcus-aurelius-stoic",
    slug: "marcus-aurelius-stoic",
    name: "Marcus Aurelius",
    nameZh: "马可·奥勒留",
    domain: ["philosophy","strategy","leadership"],
    tagline: "你拥有对思想的主权，而非外在事件。认识到这一点，你就找到了力量。",
    taglineZh: "你拥有对思想的主权，而非外在事件。认识到这一点，你就找到了力量。",
    gradientFrom: "#455a64",
    gradientTo: "#78909c",
  },
  {
    id: "wittgenstein",
    slug: "wittgenstein",
    name: "Ludwig Wittgenstein",
    nameZh: "路德维希·维特根斯坦",
    domain: ["philosophy"],
    tagline: "清晰性",
    taglineZh: "清晰性",
    gradientFrom: "#6366f1",
    gradientTo: "#8b5cf6",
  },
  {
    id: "alan-turing",
    slug: "alan-turing",
    name: "Alan Turing",
    nameZh: "艾伦·图灵",
    domain: ["science","philosophy"],
    tagline: "思考的机器",
    taglineZh: "思考的机器",
    gradientFrom: "#3b82f6",
    gradientTo: "#60a5fa",
  },
  {
    id: "aleister-crowley",
    slug: "aleister-crowley",
    name: "Aleister Crowley",
    nameZh: "阿莱斯特·克劳利",
    domain: ["spirituality"],
    tagline: "行汝意志",
    taglineZh: "行汝意志",
    gradientFrom: "#8b5cf6",
    gradientTo: "#a78bfa",
  },
  {
    id: "cao-cao",
    slug: "cao-cao",
    name: "Cao Cao",
    nameZh: "曹操",
    domain: ["history"],
    tagline: "义",
    taglineZh: "义",
    gradientFrom: "#dc2626",
    gradientTo: "#f87171",
  },
  {
    id: "carl-jung",
    slug: "carl-jung",
    name: "Carl Jung",
    nameZh: "卡尔·荣格",
    domain: ["psychology"],
    tagline: "深度理解",
    taglineZh: "深度理解",
    gradientFrom: "#f59e0b",
    gradientTo: "#fbbf24",
  },
  {
    id: "confucius",
    slug: "confucius",
    name: "Confucius",
    nameZh: "孔子",
    domain: ["philosophy"],
    tagline: "仁者爱人",
    taglineZh: "仁者爱人",
    gradientFrom: "#7c3aed",
    gradientTo: "#a78bfa",
  },
  {
    id: "einstein",
    slug: "einstein",
    name: "Albert Einstein",
    nameZh: "阿尔伯特·爱因斯坦",
    domain: ["science","philosophy"],
    tagline: "上帝不掷骰子",
    taglineZh: "上帝不掷骰子",
    gradientFrom: "#fbbf24",
    gradientTo: "#fde68a",
  },
  {
    id: "epictetus",
    slug: "epictetus",
    name: "Epictetus",
    nameZh: "爱比克泰德",
    domain: ["stoicism"],
    tagline: "内在自由",
    taglineZh: "内在自由",
    gradientFrom: "#059669",
    gradientTo: "#34d399",
  },
  {
    id: "han-fei-zi",
    slug: "han-fei-zi",
    name: "Han Fei Zi",
    nameZh: "韩非子",
    domain: ["strategy","philosophy"],
    tagline: "法治",
    taglineZh: "法治",
    gradientFrom: "#0891b2",
    gradientTo: "#22d3ee",
  },
  {
    id: "huangdi-neijing",
    slug: "huangdi-neijing",
    name: "Huang Di Nei Jing",
    nameZh: "黄帝内经",
    domain: ["medicine"],
    tagline: "治未病",
    taglineZh: "治未病",
    gradientFrom: "#16a34a",
    gradientTo: "#4ade80",
  },
  {
    id: "hui-neng",
    slug: "hui-neng",
    name: "Hui Neng",
    nameZh: "慧能",
    domain: ["zen-buddhism"],
    tagline: "智慧",
    taglineZh: "智慧",
    gradientFrom: "#ca8a04",
    gradientTo: "#eab308",
  },
  {
    id: "jack-ma",
    slug: "jack-ma",
    name: "Jack Ma",
    nameZh: "马云",
    domain: ["business"],
    tagline: "求知欲",
    taglineZh: "求知欲",
    gradientFrom: "#ea580c",
    gradientTo: "#fb923c",
  },
  {
    id: "jeff-bezos",
    slug: "jeff-bezos",
    name: "Jeff Bezos",
    nameZh: "杰夫·贝索斯",
    domain: ["business"],
    tagline: "创新",
    taglineZh: "创新",
    gradientFrom: "#2563eb",
    gradientTo: "#60a5fa",
  },
  {
    id: "john-maynard-keynes",
    slug: "john-maynard-keynes",
    name: "John Maynard Keynes",
    nameZh: "约翰·梅纳德·凯恩斯",
    domain: ["economics"],
    tagline: "经济现实主义",
    taglineZh: "经济现实主义",
    gradientFrom: "#0d9488",
    gradientTo: "#2dd4bf",
  },
  {
    id: "journey-west",
    slug: "journey-west",
    name: "Journey to the West",
    nameZh: "西游记",
    domain: ["literature"],
    tagline: "自由",
    taglineZh: "自由",
    gradientFrom: "#d97706",
    gradientTo: "#fbbf24",
  },
  {
    id: "lao-zi",
    slug: "lao-zi",
    name: "Lao Zi",
    nameZh: "老子",
    domain: ["philosophy"],
    tagline: "与道和谐",
    taglineZh: "与道和谐",
    gradientFrom: "#65a30d",
    gradientTo: "#a3e635",
  },
  {
    id: "li-chunfeng",
    slug: "li-chunfeng",
    name: "Li Chunfeng",
    nameZh: "李淳风",
    domain: ["history","science"],
    tagline: "究天人之际",
    taglineZh: "究天人之际",
    gradientFrom: "#7c3aed",
    gradientTo: "#a78bfa",
  },
  {
    id: "liu-bei",
    slug: "liu-bei",
    name: "Liu Bei",
    nameZh: "刘备",
    domain: ["history"],
    tagline: "忠义与兄弟情谊",
    taglineZh: "忠义与兄弟情谊",
    gradientFrom: "#65a30d",
    gradientTo: "#84cc16",
  },
  {
    id: "marcus-aurelius",
    slug: "marcus-aurelius",
    name: "Marcus Aurelius",
    nameZh: "马可·奥勒留",
    domain: ["stoicism"],
    tagline: "理性",
    taglineZh: "理性",
    gradientFrom: "#b45309",
    gradientTo: "#d97706",
  },
  {
    id: "mencius",
    slug: "mencius",
    name: "Mencius",
    nameZh: "孟子",
    domain: ["philosophy"],
    tagline: "仁",
    taglineZh: "仁",
    gradientFrom: "#7c3aed",
    gradientTo: "#a78bfa",
  },
  {
    id: "mo-zi",
    slug: "mo-zi",
    name: "墨子",
    nameZh: "墨子",
    domain: ["philosophy"],
    tagline: "墨家学派创始人，兼爱非攻的倡导者",
    taglineZh: "墨家学派创始人，兼爱非攻的倡导者",
    gradientFrom: "#0891b2",
    gradientTo: "#22d3ee",
  },
  {
    id: "naval-ravikant",
    slug: "naval-ravikant",
    name: "Naval Ravikant",
    nameZh: "纳瓦尔·拉维坎特",
    domain: ["investment","philosophy"],
    tagline: "慷慨",
    taglineZh: "慷慨",
    gradientFrom: "#059669",
    gradientTo: "#34d399",
  },
  {
    id: "nikola-tesla",
    slug: "nikola-tesla",
    name: "Nikola Tesla",
    nameZh: "尼古拉·特斯拉",
    domain: ["science"],
    tagline: "责任",
    taglineZh: "责任",
    gradientFrom: "#0891b2",
    gradientTo: "#22d3ee",
  },
  {
    id: "peter-thiel",
    slug: "peter-thiel",
    name: "Peter Thiel",
    nameZh: "彼得·蒂尔",
    domain: ["investment"],
    tagline: "勇敢",
    taglineZh: "勇敢",
    gradientFrom: "#1e1b4b",
    gradientTo: "#4338ca",
  },
  {
    id: "qian-xuesen",
    slug: "qian-xuesen",
    name: "Qian Xuesen",
    nameZh: "钱学森",
    domain: ["science"],
    tagline: "知识保存",
    taglineZh: "知识保存",
    gradientFrom: "#dc2626",
    gradientTo: "#f87171",
  },
  {
    id: "qu-yuan",
    slug: "qu-yuan",
    name: "Qu Yuan",
    nameZh: "屈原",
    domain: ["literature","philosophy"],
    tagline: "保存经典知识",
    taglineZh: "保存经典知识",
    gradientFrom: "#0891b2",
    gradientTo: "#22d3ee",
  },
  {
    id: "ray-dalio",
    slug: "ray-dalio",
    name: "Ray Dalio",
    nameZh: "雷·达里奥",
    domain: ["investment"],
    tagline: "正直",
    taglineZh: "正直",
    gradientFrom: "#1d4ed8",
    gradientTo: "#3b82f6",
  },
  {
    id: "records-grand-historian",
    slug: "records-grand-historian",
    name: "Sima Qian",
    nameZh: "司马迁",
    domain: ["history"],
    tagline: "德",
    taglineZh: "德",
    gradientFrom: "#7c3aed",
    gradientTo: "#a78bfa",
  },
  {
    id: "sam-altman",
    slug: "sam-altman",
    name: "Sam Altman",
    nameZh: "萨姆·阿尔特曼",
    domain: ["AI"],
    tagline: "人人繁荣",
    taglineZh: "人人繁荣",
    gradientFrom: "#10b981",
    gradientTo: "#34d399",
  },
  {
    id: "seneca",
    slug: "seneca",
    name: "Seneca",
    nameZh: "塞涅卡",
    domain: ["stoicism"],
    tagline: "自尊与尊严",
    taglineZh: "自尊与尊严",
    gradientFrom: "#b45309",
    gradientTo: "#d97706",
  },
  {
    id: "shao-yong",
    slug: "shao-yong",
    name: "Shao Yong",
    nameZh: "邵雍",
    domain: ["philosophy"],
    tagline: "观物",
    taglineZh: "观物",
    gradientFrom: "#7c3aed",
    gradientTo: "#a78bfa",
  },
  {
    id: "sima-qian",
    slug: "sima-qian",
    name: "Sima Qian",
    nameZh: "司马迁",
    domain: ["history"],
    tagline: "德治",
    taglineZh: "德治",
    gradientFrom: "#7c3aed",
    gradientTo: "#a78bfa",
  },
  {
    id: "socrates",
    slug: "socrates",
    name: "Socrates",
    nameZh: "苏格拉底",
    domain: ["philosophy"],
    tagline: "The examined life",
    taglineZh: "审视的生活",
    gradientFrom: "#6366f1",
    gradientTo: "#8b5cf6",
  },
  {
    id: "sun-tzu",
    slug: "sun-tzu",
    name: "Sun Tzu",
    nameZh: "孙子",
    domain: ["strategy"],
    tagline: "保存古典知识",
    taglineZh: "保存古典知识",
    gradientFrom: "#b45309",
    gradientTo: "#d97706",
  },
  {
    id: "sun-wukong",
    slug: "sun-wukong",
    name: "Sun Wukong",
    nameZh: "孙悟空",
    domain: ["fiction"],
    tagline: "自由",
    taglineZh: "自由",
    gradientFrom: "#dc2626",
    gradientTo: "#f87171",
  },
  {
    id: "three-kingdoms",
    slug: "three-kingdoms",
    name: "Romance of Three Kingdoms",
    nameZh: "三国演义",
    domain: ["history","literature"],
    tagline: "忠义与兄弟情谊",
    taglineZh: "忠义与兄弟情谊",
    gradientFrom: "#dc2626",
    gradientTo: "#f87171",
  },
  {
    id: "tripitaka",
    slug: "tripitaka",
    name: "Tripitaka",
    nameZh: "大唐西域记",
    domain: ["philosophy"],
    tagline: "自由",
    taglineZh: "自由",
    gradientFrom: "#ca8a04",
    gradientTo: "#eab308",
  },
  {
    id: "warren-buffett",
    slug: "warren-buffett",
    name: "Warren Buffett",
    nameZh: "沃伦·巴菲特",
    domain: ["philosophy"],
    tagline: "声誉重于金钱",
    taglineZh: "声誉重于金钱",
    gradientFrom: "#6366f1",
    gradientTo: "#8b5cf6",
  },
  {
    id: "xiang-yu",
    slug: "xiang-yu",
    name: "Xiang Yu",
    nameZh: "项羽",
    domain: ["history"],
    tagline: "力拔山兮气盖世",
    taglineZh: "力拔山兮气盖世",
    gradientFrom: "#dc2626",
    gradientTo: "#f87171",
  },
  {
    id: "zhu-bajie",
    slug: "zhu-bajie",
    name: "Zhu Bajie",
    nameZh: "猪八戒",
    domain: ["fiction"],
    tagline: "自由",
    taglineZh: "自由",
    gradientFrom: "#ea580c",
    gradientTo: "#fb923c",
  },
  {
    id: "zhuang-zi",
    slug: "zhuang-zi",
    name: "Zhuang Zi",
    nameZh: "庄子",
    domain: ["philosophy"],
    tagline: "自然",
    taglineZh: "自然",
    gradientFrom: "#65a30d",
    gradientTo: "#a3e635",
  },
  {
    id: "zhuge-liang",
    slug: "zhuge-liang",
    name: "Zhuge Liang",
    nameZh: "诸葛亮",
    domain: ["strategy","history"],
    tagline: "卧龙之志",
    taglineZh: "卧龙之志",
    gradientFrom: "#0891b2",
    gradientTo: "#22d3ee",
  },
];
