/**
 * NewsNow Bulk Fetcher
 * Fetches ALL available data sources from local NewsNow server and stores them
 * in the Prismatic PostgreSQL database (Neon).
 *
 * Usage: npx tsx scripts/fetch-newsnow.ts
 */

import { PrismaClient } from "@prisma/client"

const prisma = new PrismaClient()

// Local NewsNow server URL
const NEWSNOW_BASE = process.env.NEWSNOW_BASE_URL || "http://localhost:3444"

// ─── Source Definitions ────────────────────────────────────────────────────────
// Extracted from shared/sources.json generated by NewsNow
// Covers all enabled sources across all columns

const SOURCES: Array<{
  id: string
  name: string
  type?: string
  column?: string
  interval: number
}> = [
  // ── 国内 (china) ──
  { id: "weibo",            name: "微博",           type: "hottest",  column: "china", interval: 120000 },
  { id: "zhihu",           name: "知乎",           type: "hottest",  column: "china", interval: 600000 },
  { id: "douyin",          name: "抖音",           type: "hottest",  column: "china", interval: 600000 },
  { id: "hupu",            name: "虎扑",           type: "hottest",  column: "china", interval: 600000 },
  { id: "tieba",           name: "百度贴吧",       type: "hottest",  column: "china", interval: 600000 },
  { id: "toutiao",         name: "今日头条",       type: "hottest",  column: "china", interval: 600000 },
  { id: "bilibili-hot-search", name: "哔哩哔哩热搜", type: "hottest", column: "china", interval: 600000 },
  { id: "bilibili-hot-video",  name: "哔哩哔哩热门视频", type: "hottest", column: "china", interval: 600000 },
  { id: "bilibili-ranking",    name: "哔哩哔哩排行榜", type: "hottest", column: "china", interval: 1800000 },
  { id: "baidu",           name: "百度热搜",       type: "hottest",  column: "china", interval: 600000 },
  { id: "ifeng",           name: "凤凰网",         type: "hottest",  column: "china", interval: 600000 },
  { id: "thepaper",        name: "澎湃新闻",       type: "hottest",  column: "china", interval: 1800000 },
  { id: "nowcoder",        name: "牛客",           type: "hottest",  column: "china", interval: 600000 },
  { id: "sspai",           name: "少数派",         type: "hottest",  column: "tech",  interval: 600000 },
  { id: "juejin",          name: "稀土掘金",       type: "hottest",  column: "tech",  interval: 600000 },
  { id: "chongbuluo-hot",  name: "虫部落最热",     type: "hottest",  column: "china", interval: 1800000 },
  { id: "chongbuluo-latest", name: "虫部落最新",   type: "realtime", column: "china", interval: 1800000 },
  { id: "douban",          name: "豆瓣热门电影",   type: "hottest",  column: "china", interval: 600000 },
  { id: "freebuf",         name: "Freebuf网络安全", type: "hottest",  column: "china", interval: 600000 },
  { id: "tencent-hot",     name: "腾讯新闻早报",   type: "hottest",  column: "china", interval: 1800000 },
  { id: "qqvideo-tv-hotsearch", name: "腾讯视频热搜", type: "hottest", column: "china", interval: 1800000 },
  { id: "iqiyi-hot-ranklist",  name: "爱奇艺热播榜", type: "hottest", column: "china", interval: 1800000 },
  { id: "v2ex-share",      name: "V2EX最新分享",   type: "realtime", column: "tech",  interval: 600000 },
  { id: "kaopu",           name: "靠谱新闻",        type: "realtime", column: "world", interval: 1800000 },

  // ── 科技 (tech) ──
  { id: "hackernews",      name: "Hacker News",    type: "hottest",  column: "tech",  interval: 600000 },
  { id: "producthunt",      name: "Product Hunt",   type: "hottest",  column: "tech",  interval: 600000 },
  { id: "github-trending-today", name: "Github Today", type: "hottest", column: "tech", interval: 600000 },
  { id: "36kr-renqi",      name: "36氪人气榜",     type: "hottest",  column: "tech",  interval: 600000 },
  { id: "36kr-quick",      name: "36氪快讯",       type: "realtime", column: "tech",  interval: 300000 },
  { id: "coolapk",         name: "酷安",            type: "hottest",  column: "tech",  interval: 600000 },
  { id: "ithome",          name: "IT之家",          type: "realtime", column: "tech",  interval: 600000 },
  { id: "solidot",         name: "Solidot",         type: "realtime", column: "tech",  interval: 3600000 },
  { id: "linuxdo-hot",     name: "LINUX DO最热",    type: "hottest",  column: "tech",  interval: 1800000 },
  { id: "linuxdo-latest",   name: "LINUX DO最新",    type: "realtime", column: "tech",  interval: 600000 },
  { id: "pcbeta-windows11", name: "远景Win11论坛",   type: "realtime", column: "tech",  interval: 300000 },

  // ── 财经 (finance) ──
  { id: "wallstreetcn-quick",  name: "华尔街见闻快讯", type: "realtime", column: "finance", interval: 300000 },
  { id: "wallstreetcn-news",   name: "华尔街见闻最新", type: "realtime", column: "finance", interval: 1800000 },
  { id: "wallstreetcn-hot",    name: "华尔街见闻最热", type: "hottest",  column: "finance", interval: 1800000 },
  { id: "cls-telegraph",       name: "财联社电报",     type: "realtime", column: "finance", interval: 300000 },
  { id: "cls-depth",           name: "财联社深度",     type: "realtime", column: "finance", interval: 600000 },
  { id: "cls-hot",             name: "财联社热门",     type: "hottest",  column: "finance", interval: 600000 },
  { id: "xueqiu-hotstock",     name: "雪球热门股票",   type: "hottest",  column: "finance", interval: 120000 },
  { id: "gelonghui",           name: "格隆汇",         type: "realtime", column: "finance", interval: 120000 },
  { id: "fastbull-express",     name: "法布财经快讯",   type: "realtime", column: "finance", interval: 120000 },
  { id: "fastbull-news",       name: "法布财经头条",   type: "realtime", column: "finance", interval: 1800000 },
  { id: "jin10",               name: "金十数据",       type: "realtime", column: "finance", interval: 600000 },
  { id: "mktnews-flash",       name: "MKTNews快讯",   type: "realtime", column: "finance", interval: 120000 },

  // ── 国际 (world) ──
  { id: "zaobao",           name: "联合早报",       type: "realtime", column: "world", interval: 1800000 },
  { id: "sputniknewscn",   name: "卫星通讯社",     type: "realtime", column: "world", interval: 600000 },
  { id: "cankaoxiaoxi",     name: "参考消息",       type: "realtime", column: "world", interval: 1800000 },
  { id: "steam",           name: "Steam在线人数",  type: "hottest",  column: "world", interval: 600000 },
]

// ─── Types ────────────────────────────────────────────────────────────────────

interface NewsItemExtra {
  hover?: string
  date?: number | string
  info?: false | string
  diff?: number
  icon?: false | string | { url: string; scale: number }
}

interface NewsItem {
  id: string | number
  title: string
  url: string
  mobileUrl?: string
  pubDate?: number | string
  extra?: NewsItemExtra
}

interface SourceResponse {
  status: "success" | "cache"
  id: string
  updatedTime: number | string
  items: NewsItem[]
}

// ─── Utilities ────────────────────────────────────────────────────────────────

function sleep(ms: number) {
  return new Promise((r) => setTimeout(r, ms))
}

function getDate(): Date {
  return new Date()
}

function getTodayDate(): Date {
  const d = new Date()
  d.setHours(0, 0, 0, 0)
  return d
}

// ─── API Fetch ────────────────────────────────────────────────────────────────

async function fetchSource(sourceId: string): Promise<SourceResponse | null> {
  try {
    const res = await fetch(`${NEWSNOW_BASE}/api/s?id=${sourceId}&latest=true`, {
      signal: AbortSignal.timeout(15000),
    })
    if (!res.ok) {
      console.error(`  HTTP ${res.status} for ${sourceId}`)
      return null
    }
    return await res.json()
  } catch (err: any) {
    console.error(`  Error: ${err.message} for ${sourceId}`)
    return null
  }
}

// ─── Database Write ───────────────────────────────────────────────────────────

async function saveSnapshot(
  sourceId: string,
  sourceName: string,
  items: NewsItem[],
  fetchedAt: Date,
  snapshotDate: Date,
  status: "success" | "error" | "partial",
  errorMsg?: string
) {
  // Upsert snapshot record
  await prisma.newsSnapshot.upsert({
    where: {
      sourceId_snapshotDate: { sourceId, snapshotDate },
    },
    create: {
      sourceId,
      sourceName,
      snapshotAt: fetchedAt,
      snapshotDate,
      itemCount: items.length,
      status,
      errorMsg: errorMsg ?? null,
    },
    update: {
      snapshotAt: fetchedAt,
      itemCount: items.length,
      status,
      errorMsg: errorMsg ?? null,
    },
  })

  // Upsert items
  for (let rank = 0; rank < items.length; rank++) {
    const item = items[rank]
    const sourceItemId = String(item.id)

    const extra = item.extra ?? {}
    const info =
      extra.info && extra.info !== false ? extra.info : null
    const iconUrl =
      extra.icon && typeof extra.icon === "object"
        ? extra.icon.url
        : null
    const iconScale =
      extra.icon && typeof extra.icon === "object" ? extra.icon.scale : null

    const pubDate = item.pubDate
      ? new Date(
          typeof item.pubDate === "number"
            ? item.pubDate
            : parseInt(String(item.pubDate))
        )
      : null

    await prisma.newsItem.upsert({
      where: {
        sourceId_sourceItemId_snapshotDate: {
          sourceId,
          sourceItemId,
          snapshotDate,
        },
      },
      create: {
        sourceId,
        sourceName,
        title: item.title,
        url: item.url,
        mobileUrl: item.mobileUrl ?? null,
        pubDate,
        rank: rank + 1,
        diff: extra.diff ?? null,
        info,
        hover: extra.hover ?? null,
        iconUrl,
        iconScale,
        sourceItemId,
        fetchedAt,
        snapshotDate,
        extra: item.extra ?? undefined,
      },
      update: {
        // Already exists today — skip
      },
    })
  }
}

// ─── Main ─────────────────────────────────────────────────────────────────────

async function main() {
  console.log(
    `\n=== NewsNow Fetcher @ ${new Date().toISOString()} ===\n`
  )
  console.log(`Target: ${NEWSNOW_BASE}\n`)

  const fetchedAt = getDate()
  const snapshotDate = getTodayDate()

  const results: Array<{
    sourceId: string
    sourceName: string
    status: "success" | "error"
    count: number
    error?: string
  }> = []

  for (const source of SOURCES) {
    process.stdout.write(`[${source.column ?? "?"}] ${source.name} (${source.id})... `)

    const data = await fetchSource(source.id)
    if (!data || !data.items?.length) {
      console.log(`SKIP (no data or error)`)
      results.push({
        sourceId: source.id,
        sourceName: source.name,
        status: "error",
        count: 0,
        error: data ? "empty items" : "fetch failed",
      })

      // Still record the snapshot even on error (for tracking)
      await saveSnapshot(
        source.id,
        source.name,
        [],
        fetchedAt,
        snapshotDate,
        "error",
        data ? "empty items" : "fetch failed"
      )

      await sleep(1500)
      continue
    }

    await saveSnapshot(
      source.id,
      source.name,
      data.items,
      fetchedAt,
      snapshotDate,
      "success"
    )

    console.log(`OK (${data.items.length} items)`)
    results.push({
      sourceId: source.id,
      sourceName: source.name,
      status: "success",
      count: data.items.length,
    })

    await sleep(1500) // Be polite to the server
  }

  // ── Summary ──
  console.log(`\n${"─".repeat(60)}`)
  console.log(`SUMMARY`)
  console.log(`${"─".repeat(60)}`)

  const successCount = results.filter((r) => r.status === "success").length
  const totalItems = results.reduce((sum, r) => sum + r.count, 0)

  console.log(`Total sources:     ${results.length}`)
  console.log(`Success:            ${successCount}`)
  console.log(`Failed/Skipped:     ${results.length - successCount}`)
  console.log(`Total items stored: ${totalItems}\n`)

  // Per column summary
  const byColumn: Record<string, { total: number; ok: number; items: number }> = {}
  for (const r of results) {
    const col =
      SOURCES.find((s) => s.id === r.sourceId)?.column ?? "unknown"
    if (!byColumn[col]) byColumn[col] = { total: 0, ok: 0, items: 0 }
    byColumn[col].total++
    if (r.status === "success") byColumn[col].ok++
    byColumn[col].items += r.count
  }

  console.log(`BY COLUMN:`)
  for (const [col, s] of Object.entries(byColumn)) {
    console.log(
      `  ${col.padEnd(10)} ${String(s.ok).padStart(2)}/${String(s.total).padStart(2)} OK  ${String(s.items).padStart(4)} items`
    )
  }

  // Failed sources
  const failed = results.filter((r) => r.status === "error")
  if (failed.length > 0) {
    console.log(`\nFAILED SOURCES:`)
    for (const f of failed) {
      console.log(`  ${f.sourceName}: ${f.error}`)
    }
  }

  await prisma.$disconnect()
  console.log(`\n=== Done ===\n`)
}

main().catch((err) => {
  console.error(err)
  prisma.$disconnect().finally(() => process.exit(1))
})
